version: '3'

services:
  client:
    env_file:
      - ./.env
    build: .
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
      - ./build:/usr/src/app/build

